# ~/.cloudflared/config.yml
tunnel: 80a0f5b7-c353-47ab-891b-00846e568e7f
credentials-file: C:\Users\matlo\.cloudflared\80a0f5b7-c353-47ab-891b-00846e568e7f.json
ingress:
  - hostname: bridge.yflbridge.work
    service: http://127.0.0.1:5051
  - service: http_status:404
